<?php

namespace Proxies\__CG__\Cocorico\UserBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class User extends \Cocorico\UserBundle\Entity\User implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', 'id', 'email', 'lastName', 'firstName', 'phonePrefix', 'phone', 'birthday', 'nationality', 'countryOfResidence', 'profession', 'iban', 'bic', 'bankOwnerName', 'bankOwnerAddress', 'annualIncome', 'plainPassword', 'phoneVerified', 'emailVerified', 'idCardVerified', 'nbBookingsOfferer', 'nbBookingsAsker', 'feeAsAsker', 'feeAsOfferer', 'averageAskerRating', 'averageOffererRating', 'motherTongue', 'answerDelay', '' . "\0" . 'Cocorico\\UserBundle\\Entity\\User' . "\0" . 'messages', '' . "\0" . 'Cocorico\\UserBundle\\Entity\\User' . "\0" . 'reviewsBy', '' . "\0" . 'Cocorico\\UserBundle\\Entity\\User' . "\0" . 'reviewsTo', '' . "\0" . 'Cocorico\\UserBundle\\Entity\\User' . "\0" . 'userFacebook', '' . "\0" . 'Cocorico\\UserBundle\\Entity\\User' . "\0" . 'listings', '' . "\0" . 'Cocorico\\UserBundle\\Entity\\User' . "\0" . 'addresses', 'images', 'languages', 'bookings', '' . "\0" . 'Cocorico\\UserBundle\\Entity\\User' . "\0" . 'bookingBankWires', '' . "\0" . 'Cocorico\\UserBundle\\Entity\\User' . "\0" . 'bookingPayinRefunds', '' . "\0" . 'Cocorico\\UserBundle\\Entity\\User' . "\0" . 'listingAlerts', 'username', 'usernameCanonical', 'emailCanonical', 'enabled', 'salt', 'password', 'lastLogin', 'confirmationToken', 'passwordRequestedAt', 'groups', 'locked', 'expired', 'expiresAt', 'roles', 'credentialsExpired', 'credentialsExpireAt', 'createdAt', 'updatedAt', 'translations', 'newTranslations', 'currentLocale', 'defaultLocale', 'slug'];
        }

        return ['__isInitialized__', 'id', 'email', 'lastName', 'firstName', 'phonePrefix', 'phone', 'birthday', 'nationality', 'countryOfResidence', 'profession', 'iban', 'bic', 'bankOwnerName', 'bankOwnerAddress', 'annualIncome', 'plainPassword', 'phoneVerified', 'emailVerified', 'idCardVerified', 'nbBookingsOfferer', 'nbBookingsAsker', 'feeAsAsker', 'feeAsOfferer', 'averageAskerRating', 'averageOffererRating', 'motherTongue', 'answerDelay', '' . "\0" . 'Cocorico\\UserBundle\\Entity\\User' . "\0" . 'messages', '' . "\0" . 'Cocorico\\UserBundle\\Entity\\User' . "\0" . 'reviewsBy', '' . "\0" . 'Cocorico\\UserBundle\\Entity\\User' . "\0" . 'reviewsTo', '' . "\0" . 'Cocorico\\UserBundle\\Entity\\User' . "\0" . 'userFacebook', '' . "\0" . 'Cocorico\\UserBundle\\Entity\\User' . "\0" . 'listings', '' . "\0" . 'Cocorico\\UserBundle\\Entity\\User' . "\0" . 'addresses', 'images', 'languages', 'bookings', '' . "\0" . 'Cocorico\\UserBundle\\Entity\\User' . "\0" . 'bookingBankWires', '' . "\0" . 'Cocorico\\UserBundle\\Entity\\User' . "\0" . 'bookingPayinRefunds', '' . "\0" . 'Cocorico\\UserBundle\\Entity\\User' . "\0" . 'listingAlerts', 'username', 'usernameCanonical', 'emailCanonical', 'enabled', 'salt', 'password', 'lastLogin', 'confirmationToken', 'passwordRequestedAt', 'groups', 'locked', 'expired', 'expiresAt', 'roles', 'credentialsExpired', 'credentialsExpireAt', 'createdAt', 'updatedAt', 'translations', 'newTranslations', 'currentLocale', 'defaultLocale', 'slug'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (User $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getSluggableFields()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSluggableFields', []);

        return parent::getSluggableFields();
    }

    /**
     * {@inheritDoc}
     */
    public function __call($method, $arguments)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__call', [$method, $arguments]);

        return parent::__call($method, $arguments);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setLastName($lastName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLastName', [$lastName]);

        return parent::setLastName($lastName);
    }

    /**
     * {@inheritDoc}
     */
    public function getLastName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLastName', []);

        return parent::getLastName();
    }

    /**
     * {@inheritDoc}
     */
    public function setFirstName($firstName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFirstName', [$firstName]);

        return parent::setFirstName($firstName);
    }

    /**
     * {@inheritDoc}
     */
    public function getFirstName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFirstName', []);

        return parent::getFirstName();
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', [$email]);

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function setPhoneVerified($phoneVerified)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPhoneVerified', [$phoneVerified]);

        return parent::setPhoneVerified($phoneVerified);
    }

    /**
     * {@inheritDoc}
     */
    public function getPhoneVerified()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhoneVerified', []);

        return parent::getPhoneVerified();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmailVerified($emailVerified)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmailVerified', [$emailVerified]);

        return parent::setEmailVerified($emailVerified);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmailVerified()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmailVerified', []);

        return parent::getEmailVerified();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdCardVerified($idCardVerified)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdCardVerified', [$idCardVerified]);

        return parent::setIdCardVerified($idCardVerified);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdCardVerified()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdCardVerified', []);

        return parent::getIdCardVerified();
    }

    /**
     * {@inheritDoc}
     */
    public function setNbBookingsOfferer($nbBookingsOfferer)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNbBookingsOfferer', [$nbBookingsOfferer]);

        return parent::setNbBookingsOfferer($nbBookingsOfferer);
    }

    /**
     * {@inheritDoc}
     */
    public function getNbBookingsOfferer()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNbBookingsOfferer', []);

        return parent::getNbBookingsOfferer();
    }

    /**
     * {@inheritDoc}
     */
    public function getNbBookingsAsker()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNbBookingsAsker', []);

        return parent::getNbBookingsAsker();
    }

    /**
     * {@inheritDoc}
     */
    public function setNbBookingsAsker($nbBookingsAsker)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNbBookingsAsker', [$nbBookingsAsker]);

        return parent::setNbBookingsAsker($nbBookingsAsker);
    }

    /**
     * {@inheritDoc}
     */
    public function getFeeAsAsker()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFeeAsAsker', []);

        return parent::getFeeAsAsker();
    }

    /**
     * {@inheritDoc}
     */
    public function setFeeAsAsker($feeAsAsker)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFeeAsAsker', [$feeAsAsker]);

        return parent::setFeeAsAsker($feeAsAsker);
    }

    /**
     * {@inheritDoc}
     */
    public function getFeeAsOfferer()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFeeAsOfferer', []);

        return parent::getFeeAsOfferer();
    }

    /**
     * {@inheritDoc}
     */
    public function setFeeAsOfferer($feeAsOfferer)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFeeAsOfferer', [$feeAsOfferer]);

        return parent::setFeeAsOfferer($feeAsOfferer);
    }

    /**
     * {@inheritDoc}
     */
    public function getBirthday()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBirthday', []);

        return parent::getBirthday();
    }

    /**
     * {@inheritDoc}
     */
    public function setBirthday($birthday)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBirthday', [$birthday]);

        return parent::setBirthday($birthday);
    }

    /**
     * {@inheritDoc}
     */
    public function getNationality()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNationality', []);

        return parent::getNationality();
    }

    /**
     * {@inheritDoc}
     */
    public function setNationality($nationality)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNationality', [$nationality]);

        return parent::setNationality($nationality);
    }

    /**
     * {@inheritDoc}
     */
    public function getProfession()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProfession', []);

        return parent::getProfession();
    }

    /**
     * {@inheritDoc}
     */
    public function setProfession($profession)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProfession', [$profession]);

        return parent::setProfession($profession);
    }

    /**
     * {@inheritDoc}
     */
    public function getIban()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIban', []);

        return parent::getIban();
    }

    /**
     * {@inheritDoc}
     */
    public function setIban($iban)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIban', [$iban]);

        return parent::setIban($iban);
    }

    /**
     * {@inheritDoc}
     */
    public function getBic()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBic', []);

        return parent::getBic();
    }

    /**
     * {@inheritDoc}
     */
    public function setBic($bic)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBic', [$bic]);

        return parent::setBic($bic);
    }

    /**
     * {@inheritDoc}
     */
    public function getBankOwnerName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBankOwnerName', []);

        return parent::getBankOwnerName();
    }

    /**
     * {@inheritDoc}
     */
    public function setBankOwnerName($bankOwnerName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBankOwnerName', [$bankOwnerName]);

        return parent::setBankOwnerName($bankOwnerName);
    }

    /**
     * {@inheritDoc}
     */
    public function getBankOwnerAddress()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBankOwnerAddress', []);

        return parent::getBankOwnerAddress();
    }

    /**
     * {@inheritDoc}
     */
    public function setBankOwnerAddress($bankOwnerAddress)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBankOwnerAddress', [$bankOwnerAddress]);

        return parent::setBankOwnerAddress($bankOwnerAddress);
    }

    /**
     * {@inheritDoc}
     */
    public function getAnnualIncome()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAnnualIncome', []);

        return parent::getAnnualIncome();
    }

    /**
     * {@inheritDoc}
     */
    public function setAnnualIncome($annualIncome)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAnnualIncome', [$annualIncome]);

        return parent::setAnnualIncome($annualIncome);
    }

    /**
     * {@inheritDoc}
     */
    public function getPhone()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhone', []);

        return parent::getPhone();
    }

    /**
     * {@inheritDoc}
     */
    public function setPhone($phone)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPhone', [$phone]);

        return parent::setPhone($phone);
    }

    /**
     * {@inheritDoc}
     */
    public function getPhonePrefix()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhonePrefix', []);

        return parent::getPhonePrefix();
    }

    /**
     * {@inheritDoc}
     */
    public function setPhonePrefix($phonePrefix)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPhonePrefix', [$phonePrefix]);

        return parent::setPhonePrefix($phonePrefix);
    }

    /**
     * {@inheritDoc}
     */
    public function getCountryOfResidence()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCountryOfResidence', []);

        return parent::getCountryOfResidence();
    }

    /**
     * {@inheritDoc}
     */
    public function setCountryOfResidence($countryOfResidence)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCountryOfResidence', [$countryOfResidence]);

        return parent::setCountryOfResidence($countryOfResidence);
    }

    /**
     * {@inheritDoc}
     */
    public function setAverageAskerRating($averageAskerRating)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAverageAskerRating', [$averageAskerRating]);

        return parent::setAverageAskerRating($averageAskerRating);
    }

    /**
     * {@inheritDoc}
     */
    public function getAverageAskerRating()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAverageAskerRating', []);

        return parent::getAverageAskerRating();
    }

    /**
     * {@inheritDoc}
     */
    public function setAverageOffererRating($averageOffererRating)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAverageOffererRating', [$averageOffererRating]);

        return parent::setAverageOffererRating($averageOffererRating);
    }

    /**
     * {@inheritDoc}
     */
    public function getAverageOffererRating()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAverageOffererRating', []);

        return parent::getAverageOffererRating();
    }

    /**
     * {@inheritDoc}
     */
    public function setAnswerDelay($answerDelay)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAnswerDelay', [$answerDelay]);

        return parent::setAnswerDelay($answerDelay);
    }

    /**
     * {@inheritDoc}
     */
    public function getAnswerDelay()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAnswerDelay', []);

        return parent::getAnswerDelay();
    }

    /**
     * {@inheritDoc}
     */
    public function getMotherTongue()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMotherTongue', []);

        return parent::getMotherTongue();
    }

    /**
     * {@inheritDoc}
     */
    public function setMotherTongue($motherTongue)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMotherTongue', [$motherTongue]);

        return parent::setMotherTongue($motherTongue);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserFacebook()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserFacebook', []);

        return parent::getUserFacebook();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserFacebook($userFacebook)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserFacebook', [$userFacebook]);

        return parent::setUserFacebook($userFacebook);
    }

    /**
     * {@inheritDoc}
     */
    public function getFullName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFullName', []);

        return parent::getFullName();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function addListing(\Cocorico\CoreBundle\Entity\Listing $listing)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addListing', [$listing]);

        return parent::addListing($listing);
    }

    /**
     * {@inheritDoc}
     */
    public function removeListing(\Cocorico\CoreBundle\Entity\Listing $listing)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeListing', [$listing]);

        return parent::removeListing($listing);
    }

    /**
     * {@inheritDoc}
     */
    public function getListings()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getListings', []);

        return parent::getListings();
    }

    /**
     * {@inheritDoc}
     */
    public function addImage(\Cocorico\UserBundle\Entity\UserImage $image)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addImage', [$image]);

        return parent::addImage($image);
    }

    /**
     * {@inheritDoc}
     */
    public function removeImage(\Cocorico\UserBundle\Entity\UserImage $image)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeImage', [$image]);

        return parent::removeImage($image);
    }

    /**
     * {@inheritDoc}
     */
    public function getImages()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImages', []);

        return parent::getImages();
    }

    /**
     * {@inheritDoc}
     */
    public function addLanguage(\Cocorico\UserBundle\Entity\UserLanguage $language)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addLanguage', [$language]);

        return parent::addLanguage($language);
    }

    /**
     * {@inheritDoc}
     */
    public function removeLanguage(\Cocorico\UserBundle\Entity\UserLanguage $language)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeLanguage', [$language]);

        return parent::removeLanguage($language);
    }

    /**
     * {@inheritDoc}
     */
    public function getLanguages()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLanguages', []);

        return parent::getLanguages();
    }

    /**
     * {@inheritDoc}
     */
    public function getBookings()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBookings', []);

        return parent::getBookings();
    }

    /**
     * {@inheritDoc}
     */
    public function setBookings(\Doctrine\Common\Collections\ArrayCollection $bookings)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBookings', [$bookings]);

        return parent::setBookings($bookings);
    }

    /**
     * {@inheritDoc}
     */
    public function getMessages()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMessages', []);

        return parent::getMessages();
    }

    /**
     * {@inheritDoc}
     */
    public function setMessages(\Doctrine\Common\Collections\ArrayCollection $messages)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMessages', [$messages]);

        return parent::setMessages($messages);
    }

    /**
     * {@inheritDoc}
     */
    public function getReviewsBy()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReviewsBy', []);

        return parent::getReviewsBy();
    }

    /**
     * {@inheritDoc}
     */
    public function setReviewsBy(\Doctrine\Common\Collections\ArrayCollection $reviewsBy)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReviewsBy', [$reviewsBy]);

        return parent::setReviewsBy($reviewsBy);
    }

    /**
     * {@inheritDoc}
     */
    public function getReviewsTo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReviewsTo', []);

        return parent::getReviewsTo();
    }

    /**
     * {@inheritDoc}
     */
    public function setReviewsTo(\Doctrine\Common\Collections\ArrayCollection $reviewsTo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReviewsTo', [$reviewsTo]);

        return parent::setReviewsTo($reviewsTo);
    }

    /**
     * {@inheritDoc}
     */
    public function addAddress(\Cocorico\UserBundle\Entity\UserAddress $address)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addAddress', [$address]);

        return parent::addAddress($address);
    }

    /**
     * {@inheritDoc}
     */
    public function removeAddress(\Cocorico\UserBundle\Entity\UserAddress $address)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeAddress', [$address]);

        return parent::removeAddress($address);
    }

    /**
     * {@inheritDoc}
     */
    public function getAddresses()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAddresses', []);

        return parent::getAddresses();
    }

    /**
     * {@inheritDoc}
     */
    public function getAddressesOfType($type)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAddressesOfType', [$type]);

        return parent::getAddressesOfType($type);
    }

    /**
     * {@inheritDoc}
     */
    public function getBookingBankWires()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBookingBankWires', []);

        return parent::getBookingBankWires();
    }

    /**
     * {@inheritDoc}
     */
    public function setBookingBankWires(\Doctrine\Common\Collections\ArrayCollection $bookingBankWires)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBookingBankWires', [$bookingBankWires]);

        return parent::setBookingBankWires($bookingBankWires);
    }

    /**
     * {@inheritDoc}
     */
    public function getBookingPayinRefunds()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBookingPayinRefunds', []);

        return parent::getBookingPayinRefunds();
    }

    /**
     * {@inheritDoc}
     */
    public function setBookingPayinRefunds(\Doctrine\Common\Collections\ArrayCollection $bookingPayinRefunds)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBookingPayinRefunds', [$bookingPayinRefunds]);

        return parent::setBookingPayinRefunds($bookingPayinRefunds);
    }

    /**
     * {@inheritDoc}
     */
    public function addListingAlert($listingAlert)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addListingAlert', [$listingAlert]);

        return parent::addListingAlert($listingAlert);
    }

    /**
     * {@inheritDoc}
     */
    public function removeListingAlert($listingAlert)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeListingAlert', [$listingAlert]);

        return parent::removeListingAlert($listingAlert);
    }

    /**
     * {@inheritDoc}
     */
    public function getListingAlerts()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getListingAlerts', []);

        return parent::getListingAlerts();
    }

    /**
     * {@inheritDoc}
     */
    public function setListingAlerts(\Doctrine\Common\Collections\ArrayCollection $listingAlerts)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setListingAlerts', [$listingAlerts]);

        return parent::setListingAlerts($listingAlerts);
    }

    /**
     * {@inheritDoc}
     */
    public function getCompletionInformations($minImages, $strict = true)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCompletionInformations', [$minImages, $strict]);

        return parent::getCompletionInformations($minImages, $strict);
    }

    /**
     * {@inheritDoc}
     */
    public function guessPreferredLanguage($siteLocales, $defaultLocale)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'guessPreferredLanguage', [$siteLocales, $defaultLocale]);

        return parent::guessPreferredLanguage($siteLocales, $defaultLocale);
    }

    /**
     * {@inheritDoc}
     */
    public function addRole($role)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addRole', [$role]);

        return parent::addRole($role);
    }

    /**
     * {@inheritDoc}
     */
    public function serialize()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'serialize', []);

        return parent::serialize();
    }

    /**
     * {@inheritDoc}
     */
    public function unserialize($serialized)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'unserialize', [$serialized]);

        return parent::unserialize($serialized);
    }

    /**
     * {@inheritDoc}
     */
    public function eraseCredentials()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'eraseCredentials', []);

        return parent::eraseCredentials();
    }

    /**
     * {@inheritDoc}
     */
    public function getUsername()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsername', []);

        return parent::getUsername();
    }

    /**
     * {@inheritDoc}
     */
    public function getUsernameCanonical()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsernameCanonical', []);

        return parent::getUsernameCanonical();
    }

    /**
     * {@inheritDoc}
     */
    public function getSalt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSalt', []);

        return parent::getSalt();
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', []);

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function getEmailCanonical()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmailCanonical', []);

        return parent::getEmailCanonical();
    }

    /**
     * {@inheritDoc}
     */
    public function getPassword()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPassword', []);

        return parent::getPassword();
    }

    /**
     * {@inheritDoc}
     */
    public function getPlainPassword()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPlainPassword', []);

        return parent::getPlainPassword();
    }

    /**
     * {@inheritDoc}
     */
    public function getLastLogin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLastLogin', []);

        return parent::getLastLogin();
    }

    /**
     * {@inheritDoc}
     */
    public function getConfirmationToken()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getConfirmationToken', []);

        return parent::getConfirmationToken();
    }

    /**
     * {@inheritDoc}
     */
    public function getRoles()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRoles', []);

        return parent::getRoles();
    }

    /**
     * {@inheritDoc}
     */
    public function hasRole($role)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'hasRole', [$role]);

        return parent::hasRole($role);
    }

    /**
     * {@inheritDoc}
     */
    public function isAccountNonExpired()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isAccountNonExpired', []);

        return parent::isAccountNonExpired();
    }

    /**
     * {@inheritDoc}
     */
    public function isAccountNonLocked()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isAccountNonLocked', []);

        return parent::isAccountNonLocked();
    }

    /**
     * {@inheritDoc}
     */
    public function isCredentialsNonExpired()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isCredentialsNonExpired', []);

        return parent::isCredentialsNonExpired();
    }

    /**
     * {@inheritDoc}
     */
    public function isCredentialsExpired()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isCredentialsExpired', []);

        return parent::isCredentialsExpired();
    }

    /**
     * {@inheritDoc}
     */
    public function isEnabled()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isEnabled', []);

        return parent::isEnabled();
    }

    /**
     * {@inheritDoc}
     */
    public function isExpired()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isExpired', []);

        return parent::isExpired();
    }

    /**
     * {@inheritDoc}
     */
    public function isLocked()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isLocked', []);

        return parent::isLocked();
    }

    /**
     * {@inheritDoc}
     */
    public function isSuperAdmin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isSuperAdmin', []);

        return parent::isSuperAdmin();
    }

    /**
     * {@inheritDoc}
     */
    public function isUser(\FOS\UserBundle\Model\UserInterface $user = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isUser', [$user]);

        return parent::isUser($user);
    }

    /**
     * {@inheritDoc}
     */
    public function removeRole($role)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeRole', [$role]);

        return parent::removeRole($role);
    }

    /**
     * {@inheritDoc}
     */
    public function setUsername($username)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsername', [$username]);

        return parent::setUsername($username);
    }

    /**
     * {@inheritDoc}
     */
    public function setUsernameCanonical($usernameCanonical)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsernameCanonical', [$usernameCanonical]);

        return parent::setUsernameCanonical($usernameCanonical);
    }

    /**
     * {@inheritDoc}
     */
    public function setCredentialsExpireAt(\DateTime $date)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCredentialsExpireAt', [$date]);

        return parent::setCredentialsExpireAt($date);
    }

    /**
     * {@inheritDoc}
     */
    public function setCredentialsExpired($boolean)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCredentialsExpired', [$boolean]);

        return parent::setCredentialsExpired($boolean);
    }

    /**
     * {@inheritDoc}
     */
    public function setEmailCanonical($emailCanonical)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmailCanonical', [$emailCanonical]);

        return parent::setEmailCanonical($emailCanonical);
    }

    /**
     * {@inheritDoc}
     */
    public function setEnabled($boolean)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEnabled', [$boolean]);

        return parent::setEnabled($boolean);
    }

    /**
     * {@inheritDoc}
     */
    public function setExpired($boolean)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExpired', [$boolean]);

        return parent::setExpired($boolean);
    }

    /**
     * {@inheritDoc}
     */
    public function setExpiresAt(\DateTime $date)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExpiresAt', [$date]);

        return parent::setExpiresAt($date);
    }

    /**
     * {@inheritDoc}
     */
    public function setPassword($password)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPassword', [$password]);

        return parent::setPassword($password);
    }

    /**
     * {@inheritDoc}
     */
    public function setSuperAdmin($boolean)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSuperAdmin', [$boolean]);

        return parent::setSuperAdmin($boolean);
    }

    /**
     * {@inheritDoc}
     */
    public function setPlainPassword($password)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPlainPassword', [$password]);

        return parent::setPlainPassword($password);
    }

    /**
     * {@inheritDoc}
     */
    public function setLastLogin(\DateTime $time)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLastLogin', [$time]);

        return parent::setLastLogin($time);
    }

    /**
     * {@inheritDoc}
     */
    public function setLocked($boolean)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLocked', [$boolean]);

        return parent::setLocked($boolean);
    }

    /**
     * {@inheritDoc}
     */
    public function setConfirmationToken($confirmationToken)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setConfirmationToken', [$confirmationToken]);

        return parent::setConfirmationToken($confirmationToken);
    }

    /**
     * {@inheritDoc}
     */
    public function setPasswordRequestedAt(\DateTime $date = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPasswordRequestedAt', [$date]);

        return parent::setPasswordRequestedAt($date);
    }

    /**
     * {@inheritDoc}
     */
    public function getPasswordRequestedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPasswordRequestedAt', []);

        return parent::getPasswordRequestedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function isPasswordRequestNonExpired($ttl)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isPasswordRequestNonExpired', [$ttl]);

        return parent::isPasswordRequestNonExpired($ttl);
    }

    /**
     * {@inheritDoc}
     */
    public function setRoles(array $roles)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRoles', [$roles]);

        return parent::setRoles($roles);
    }

    /**
     * {@inheritDoc}
     */
    public function getGroups()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGroups', []);

        return parent::getGroups();
    }

    /**
     * {@inheritDoc}
     */
    public function getGroupNames()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGroupNames', []);

        return parent::getGroupNames();
    }

    /**
     * {@inheritDoc}
     */
    public function hasGroup($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'hasGroup', [$name]);

        return parent::hasGroup($name);
    }

    /**
     * {@inheritDoc}
     */
    public function addGroup(\FOS\UserBundle\Model\GroupInterface $group)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addGroup', [$group]);

        return parent::addGroup($group);
    }

    /**
     * {@inheritDoc}
     */
    public function removeGroup(\FOS\UserBundle\Model\GroupInterface $group)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeGroup', [$group]);

        return parent::removeGroup($group);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', []);

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedAt', []);

        return parent::getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAt(\DateTime $createdAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', [$createdAt]);

        return parent::setCreatedAt($createdAt);
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedAt(\DateTime $updatedAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedAt', [$updatedAt]);

        return parent::setUpdatedAt($updatedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function updateTimestamps()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'updateTimestamps', []);

        return parent::updateTimestamps();
    }

    /**
     * {@inheritDoc}
     */
    public function getTranslations()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTranslations', []);

        return parent::getTranslations();
    }

    /**
     * {@inheritDoc}
     */
    public function getNewTranslations()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNewTranslations', []);

        return parent::getNewTranslations();
    }

    /**
     * {@inheritDoc}
     */
    public function addTranslation($translation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addTranslation', [$translation]);

        return parent::addTranslation($translation);
    }

    /**
     * {@inheritDoc}
     */
    public function removeTranslation($translation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeTranslation', [$translation]);

        return parent::removeTranslation($translation);
    }

    /**
     * {@inheritDoc}
     */
    public function translate($locale = NULL, $fallbackToDefault = true)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'translate', [$locale, $fallbackToDefault]);

        return parent::translate($locale, $fallbackToDefault);
    }

    /**
     * {@inheritDoc}
     */
    public function mergeNewTranslations()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'mergeNewTranslations', []);

        return parent::mergeNewTranslations();
    }

    /**
     * {@inheritDoc}
     */
    public function setCurrentLocale($locale)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCurrentLocale', [$locale]);

        return parent::setCurrentLocale($locale);
    }

    /**
     * {@inheritDoc}
     */
    public function getCurrentLocale()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCurrentLocale', []);

        return parent::getCurrentLocale();
    }

    /**
     * {@inheritDoc}
     */
    public function setDefaultLocale($locale)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDefaultLocale', [$locale]);

        return parent::setDefaultLocale($locale);
    }

    /**
     * {@inheritDoc}
     */
    public function getDefaultLocale()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDefaultLocale', []);

        return parent::getDefaultLocale();
    }

    /**
     * {@inheritDoc}
     */
    public function setSlug($slug)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSlug', [$slug]);

        return parent::setSlug($slug);
    }

    /**
     * {@inheritDoc}
     */
    public function getSlug()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSlug', []);

        return parent::getSlug();
    }

    /**
     * {@inheritDoc}
     */
    public function generateSlug()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'generateSlug', []);

        return parent::generateSlug();
    }

}
