imports:
    - { resource: "@CocoricoCoreBundle/Resources/config/parameters.yml"}
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: "@CocoricoCoreBundle/Resources/config/config.yml"}
    - { resource: "@CocoricoUserBundle/Resources/config/config.yml"}
    - { resource: "@CocoricoMessageBundle/Resources/config/config.yml"}
    - { resource: "@CocoricoGeoBundle/Resources/config/config.yml"}
    - { resource: "@CocoricoBreadcrumbBundle/Resources/config/config.yml"}
    - { resource: "@CocoricoPageBundle/Resources/config/config.yml"}
    - { resource: "@CocoricoConfigBundle/Resources/config/config.yml"}

framework:
    #esi:             ~
    translator:      { fallback: "%cocorico.locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%cocorico.locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
        name: _csess
        #on debian there is a /etc/cron.d/php5 doing the job
        gc_probability: 0
    fragments:       ~
    http_method_override: true


# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    cache:  false

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller:
        enabled:    false

    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        minifycsscompressor: ~
        jsqueeze: ~
#        jsminplus: ~
#        closure:
#            jar: "%kernel.root_dir%/Resources/java/compiler.jar"
#        yui_css:
#            jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
#        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

doctrine_mongodb:
    connections:
        default:
            server: "%mongodb_server%"
            options: {}
    default_database: "%mongodb_database_name%"
    document_managers:
        default:
            auto_mapping: true


# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    port:      "%mailer_port%"
    spool:     { type: memory }


doctrine_migrations:
    dir_name: "%kernel.root_dir%/DoctrineMigrations"
    namespace: Application\Migrations
    table_name: migration_versions
    name: Application Migrations
    
# payment core module    
#jms_payment_core:
#    encryption:
#        secret: 7c222fb2927d828af22f592134e8932480637c0d # 12345678 in SHA1
  
# PayPal     
jms_payment_paypal:
    username: admin@koduteenus.online
    password: cocorico
    signature: access_token$sandbox$f2w97x7m8z2f87w8$437facced3d661be48193da7568d83a9
    debug: true # when true, connect to PayPal sandbox; uses kernel debug value when not specified

# mangopay    
troopers_mangopay:
    client_id: koduteenus_mangopay1
    client_password: Tanusree_1
    base_url: 'https://api.sandbox.mangopay.com'
    #api_key: VwtUxgPUQk51S1Ww2rUkCCWQsmazo8s58B0hEREWeS5mSUjUjr