<?php

namespace Hydrators;

use Doctrine\ODM\MongoDB\DocumentManager;
use Doctrine\ODM\MongoDB\Mapping\ClassMetadata;
use Doctrine\ODM\MongoDB\Hydrator\HydratorInterface;
use Doctrine\ODM\MongoDB\Query\Query;
use Doctrine\ODM\MongoDB\UnitOfWork;
use Doctrine\ODM\MongoDB\Mapping\ClassMetadataInfo;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ODM. DO NOT EDIT THIS FILE.
 */
class FOSMessageBundleDocumentThreadMetadataHydrator implements HydratorInterface
{
    private $dm;
    private $unitOfWork;
    private $class;

    public function __construct(DocumentManager $dm, UnitOfWork $uow, ClassMetadata $class)
    {
        $this->dm = $dm;
        $this->unitOfWork = $uow;
        $this->class = $class;
    }

    public function hydrate($document, $data, array $hints = array())
    {
        $hydratedData = array();

        /** @Field(type="boolean") */
        if (isset($data['isDeleted']) || (! empty($this->class->fieldMappings['isDeleted']['nullable']) && array_key_exists('isDeleted', $data))) {
            $value = $data['isDeleted'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['isDeleted']['type'];
                $return = (bool) $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['isDeleted']->setValue($document, $return);
            $hydratedData['isDeleted'] = $return;
        }

        /** @Field(type="date") */
        if (isset($data['lastParticipantMessageDate'])) {
            $value = $data['lastParticipantMessageDate'];
            if ($value === null) { $return = null; } else { $return = \Doctrine\ODM\MongoDB\Types\DateType::getDateTime($value); }
            $this->class->reflFields['lastParticipantMessageDate']->setValue($document, clone $return);
            $hydratedData['lastParticipantMessageDate'] = $return;
        }

        /** @Field(type="date") */
        if (isset($data['lastMessageDate'])) {
            $value = $data['lastMessageDate'];
            if ($value === null) { $return = null; } else { $return = \Doctrine\ODM\MongoDB\Types\DateType::getDateTime($value); }
            $this->class->reflFields['lastMessageDate']->setValue($document, clone $return);
            $hydratedData['lastMessageDate'] = $return;
        }
        return $hydratedData;
    }
}