<?php

namespace Cocorico\BreadcrumbBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class BreadcrumbsController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Cocorico\BreadcrumbBundle\Controller\BreadcrumbsController();
        return $instance;
    }
}
