<?php

namespace Cocorico\UserBundle\Controller\Frontend;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class ChangePasswordController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Cocorico\UserBundle\Controller\Frontend\ChangePasswordController();
        return $instance;
    }
}
