<?php

namespace Cocorico\UserBundle\Controller\Dashboard;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class ProfileContactController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Cocorico\UserBundle\Controller\Dashboard\ProfileContactController();
        return $instance;
    }
}
