<?php

namespace Cocorico\UserBundle\Controller\Admin;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class UserAdminController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Cocorico\UserBundle\Controller\Admin\UserAdminController();
        return $instance;
    }
}
