<?php

namespace Cocorico\CMSBundle\Controller\Frontend;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class FooterController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Cocorico\CMSBundle\Controller\Frontend\FooterController();
        return $instance;
    }
}
