<?php

namespace Cocorico\MessageBundle\Controller\Dashboard;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class MessageController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Cocorico\MessageBundle\Controller\Dashboard\MessageController();
        return $instance;
    }
}
