<?php

namespace Cocorico\GeoBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class GeocodingController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Cocorico\GeoBundle\Controller\GeocodingController();
        return $instance;
    }
}
