<?php

namespace Cocorico\ContactBundle\Controller\Frontend;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class ContactController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Cocorico\ContactBundle\Controller\Frontend\ContactController();
        return $instance;
    }
}
