<?php

namespace Cocorico\CoreBundle\Controller\Dashboard\Asker;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class BookingPayinController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Cocorico\CoreBundle\Controller\Dashboard\Asker\BookingPayinController();
        return $instance;
    }
}
