<?php

namespace Cocorico\ReviewBundle\Controller\Dashboard;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class ReviewController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Cocorico\ReviewBundle\Controller\Dashboard\ReviewController();
        return $instance;
    }
}
