<?php

namespace Cocorico\CoreBundle\Controller\Frontend;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class ListingAvailabilityController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Cocorico\CoreBundle\Controller\Frontend\ListingAvailabilityController();
        return $instance;
    }
}
