<?php

namespace Cocorico\CoreBundle\Controller\Dashboard\Offerer;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class ListingAvailabilityStatusController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Cocorico\CoreBundle\Controller\Dashboard\Offerer\ListingAvailabilityStatusController();
        return $instance;
    }
}
