<?php

namespace FOS\MessageBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class MessageController__JMSInjector
{
    public static function inject($container) {
        $instance = new \FOS\MessageBundle\Controller\MessageController();
        return $instance;
    }
}
