<?php

namespace Troopers\MangopayBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class PaymentController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Troopers\MangopayBundle\Controller\PaymentController();
        return $instance;
    }
}
