<?php

namespace Hydrators;

use Doctrine\ODM\MongoDB\DocumentManager;
use Doctrine\ODM\MongoDB\Mapping\ClassMetadata;
use Doctrine\ODM\MongoDB\Hydrator\HydratorInterface;
use Doctrine\ODM\MongoDB\Query\Query;
use Doctrine\ODM\MongoDB\UnitOfWork;
use Doctrine\ODM\MongoDB\Mapping\ClassMetadataInfo;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ODM. DO NOT EDIT THIS FILE.
 */
class CocoricoCoreBundleDocumentListingAvailabilityHydrator implements HydratorInterface
{
    private $dm;
    private $unitOfWork;
    private $class;

    public function __construct(DocumentManager $dm, UnitOfWork $uow, ClassMetadata $class)
    {
        $this->dm = $dm;
        $this->unitOfWork = $uow;
        $this->class = $class;
    }

    public function hydrate($document, $data, array $hints = array())
    {
        $hydratedData = array();

        /** @Field(type="id") */
        if (isset($data['_id']) || (! empty($this->class->fieldMappings['id']['nullable']) && array_key_exists('_id', $data))) {
            $value = $data['_id'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['id']['type'];
                $return = $value instanceof \MongoId ? (string) $value : $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['id']->setValue($document, $return);
            $hydratedData['id'] = $return;
        }

        /** @Field(type="int") */
        if (isset($data['lId']) || (! empty($this->class->fieldMappings['listingId']['nullable']) && array_key_exists('lId', $data))) {
            $value = $data['lId'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['listingId']['type'];
                $return = (int) $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['listingId']->setValue($document, $return);
            $hydratedData['listingId'] = $return;
        }

        /** @Field(type="date") */
        if (isset($data['d'])) {
            $value = $data['d'];
            if ($value === null) { $return = null; } else { $return = \Doctrine\ODM\MongoDB\Types\DateType::getDateTime($value); }
            $this->class->reflFields['day']->setValue($document, clone $return);
            $hydratedData['day'] = $return;
        }

        /** @Field(type="int") */
        if (isset($data['s']) || (! empty($this->class->fieldMappings['status']['nullable']) && array_key_exists('s', $data))) {
            $value = $data['s'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['status']['type'];
                $return = (int) $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['status']->setValue($document, $return);
            $hydratedData['status'] = $return;
        }

        /** @Field(type="int") */
        if (isset($data['p']) || (! empty($this->class->fieldMappings['price']['nullable']) && array_key_exists('p', $data))) {
            $value = $data['p'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['price']['type'];
                $return = (int) $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['price']->setValue($document, $return);
            $hydratedData['price'] = $return;
        }

        /** @Many */
        $mongoData = isset($data['ts']) ? $data['ts'] : null;
        $return = $this->dm->getConfiguration()->getPersistentCollectionFactory()->create($this->dm, $this->class->fieldMappings['times']);
        $return->setHints($hints);
        $return->setOwner($document, $this->class->fieldMappings['times']);
        $return->setInitialized(false);
        if ($mongoData) {
            $return->setMongoData($mongoData);
        }
        $this->class->reflFields['times']->setValue($document, $return);
        $hydratedData['times'] = $return;
        return $hydratedData;
    }
}