<?php

namespace Hydrators;

use Doctrine\ODM\MongoDB\DocumentManager;
use Doctrine\ODM\MongoDB\Mapping\ClassMetadata;
use Doctrine\ODM\MongoDB\Hydrator\HydratorInterface;
use Doctrine\ODM\MongoDB\Query\Query;
use Doctrine\ODM\MongoDB\UnitOfWork;
use Doctrine\ODM\MongoDB\Mapping\ClassMetadataInfo;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ODM. DO NOT EDIT THIS FILE.
 */
class FOSMessageBundleDocumentMessageMetadataHydrator implements HydratorInterface
{
    private $dm;
    private $unitOfWork;
    private $class;

    public function __construct(DocumentManager $dm, UnitOfWork $uow, ClassMetadata $class)
    {
        $this->dm = $dm;
        $this->unitOfWork = $uow;
        $this->class = $class;
    }

    public function hydrate($document, $data, array $hints = array())
    {
        $hydratedData = array();

        /** @Field(type="boolean") */
        if (isset($data['isRead']) || (! empty($this->class->fieldMappings['isRead']['nullable']) && array_key_exists('isRead', $data))) {
            $value = $data['isRead'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['isRead']['type'];
                $return = (bool) $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['isRead']->setValue($document, $return);
            $hydratedData['isRead'] = $return;
        }
        return $hydratedData;
    }
}