<?php

namespace Hydrators;

use Doctrine\ODM\MongoDB\DocumentManager;
use Doctrine\ODM\MongoDB\Mapping\ClassMetadata;
use Doctrine\ODM\MongoDB\Hydrator\HydratorInterface;
use Doctrine\ODM\MongoDB\Query\Query;
use Doctrine\ODM\MongoDB\UnitOfWork;
use Doctrine\ODM\MongoDB\Mapping\ClassMetadataInfo;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ODM. DO NOT EDIT THIS FILE.
 */
class FOSMessageBundleDocumentThreadHydrator implements HydratorInterface
{
    private $dm;
    private $unitOfWork;
    private $class;

    public function __construct(DocumentManager $dm, UnitOfWork $uow, ClassMetadata $class)
    {
        $this->dm = $dm;
        $this->unitOfWork = $uow;
        $this->class = $class;
    }

    public function hydrate($document, $data, array $hints = array())
    {
        $hydratedData = array();

        /** @Field(type="string") */
        if (isset($data['subject']) || (! empty($this->class->fieldMappings['subject']['nullable']) && array_key_exists('subject', $data))) {
            $value = $data['subject'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['subject']['type'];
                $return = (string) $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['subject']->setValue($document, $return);
            $hydratedData['subject'] = $return;
        }

        /** @Field(type="date") */
        if (isset($data['createdAt'])) {
            $value = $data['createdAt'];
            if ($value === null) { $return = null; } else { $return = \Doctrine\ODM\MongoDB\Types\DateType::getDateTime($value); }
            $this->class->reflFields['createdAt']->setValue($document, clone $return);
            $hydratedData['createdAt'] = $return;
        }

        /** @Field(type="date") */
        if (isset($data['lastMessageDate'])) {
            $value = $data['lastMessageDate'];
            if ($value === null) { $return = null; } else { $return = \Doctrine\ODM\MongoDB\Types\DateType::getDateTime($value); }
            $this->class->reflFields['lastMessageDate']->setValue($document, clone $return);
            $hydratedData['lastMessageDate'] = $return;
        }

        /** @Field(type="boolean") */
        if (isset($data['isSpam']) || (! empty($this->class->fieldMappings['isSpam']['nullable']) && array_key_exists('isSpam', $data))) {
            $value = $data['isSpam'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['isSpam']['type'];
                $return = (bool) $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['isSpam']->setValue($document, $return);
            $hydratedData['isSpam'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['keywords']) || (! empty($this->class->fieldMappings['keywords']['nullable']) && array_key_exists('keywords', $data))) {
            $value = $data['keywords'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['keywords']['type'];
                $return = (string) $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['keywords']->setValue($document, $return);
            $hydratedData['keywords'] = $return;
        }

        /** @Field(type="collection") */
        if (isset($data['activeParticipants']) || (! empty($this->class->fieldMappings['activeParticipants']['nullable']) && array_key_exists('activeParticipants', $data))) {
            $value = $data['activeParticipants'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['activeParticipants']['type'];
                $return = $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['activeParticipants']->setValue($document, $return);
            $hydratedData['activeParticipants'] = $return;
        }

        /** @Field(type="collection") */
        if (isset($data['activeRecipients']) || (! empty($this->class->fieldMappings['activeRecipients']['nullable']) && array_key_exists('activeRecipients', $data))) {
            $value = $data['activeRecipients'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['activeRecipients']['type'];
                $return = $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['activeRecipients']->setValue($document, $return);
            $hydratedData['activeRecipients'] = $return;
        }

        /** @Field(type="collection") */
        if (isset($data['activeSenders']) || (! empty($this->class->fieldMappings['activeSenders']['nullable']) && array_key_exists('activeSenders', $data))) {
            $value = $data['activeSenders'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['activeSenders']['type'];
                $return = $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['activeSenders']->setValue($document, $return);
            $hydratedData['activeSenders'] = $return;
        }
        return $hydratedData;
    }
}